proxmox_url          = "https://edge-pve-01.lan.homelab:8006/api2/json"
node                 = "edge-pve-01"
vm_id                = 921
build_name           = "ubuntu"
vm_name              = "ubuntu-24-04-desktop-raw"
clone_vm             = "ubuntu-24-04-server-raw"
template_description = "Ubuntu desktop 24.04 template with the bare minimum configuration generated by Packer on {{ isotime `2006-01-02` }}."

vga = {
  type   = "std",
  memory = 32
}
