# Proxmox authentication
proxmox_url = "https://edge-pve-01.lan.homelab:8006/api2/json"

# Clone
clone_vm = "ubuntu-24-04-server-raw"

# General
node                 = "edge-pve-01"
vm_id                = 910
vm_name              = "ubuntu-24-04-desktop-raw"
pool                 = "Template"
template_description = "Ubuntu desktop 24.04 template with the bare minimum configuration generated by Packer on {{ isotime `2006-01-02 15:04` }}."

# Cloud-Init
cloud_init_storage_pool = "Ceph_Gold"

# OS
vga = {
  type   = "virtio-gl",
  memory = 128
}
