---
- name: "Check if renderer line exists in netplan"
  ansible.builtin.lineinfile:
    path: "/etc/netplan/50-cloud-init.yaml"
    regexp: "^\\s+renderer:"
    state: "absent"
  check_mode: true
  register: renderer_check

- name: "Adding the NetworkManager in the netplan config file"
  ansible.builtin.lineinfile:
    path: "/etc/netplan/50-cloud-init.yaml"
    insertafter: "^network:"
    line: "  renderer: NetworkManager"
    state: "present"
  when: not renderer_check.changed
  notify:
    - "Netplan Apply"

- name: "Disabling systemd-networkd service"
  ansible.builtin.systemd:
    name: "systemd-networkd"
    enabled: false
